version: "3.8"

services:
  nginx:
    container_name: fc-nginx
    image: nginx:alpine
    depends_on:
      - php-fpm
    ports:
      - '${APP_PORT:-8080}:80'
    volumes:
      - ./:/app
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=Asia/Tokyo

  php-fpm:
    container_name: fc-php
    build:
      context: ./docker
      dockerfile: php/Dockerfile
      args:
        - TZ=Asia/Tokyo
    # user: '${UID:-1000}:${GID:-1000}'
    volumes:
      - ./:/app
      - ./docker/php/logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/supervisor/supervisord.conf:/etc/supervisord.conf
      - ./docker/cron/scheduler:/etc/cron.d/scheduler
    working_dir: /app
    links:
      - mysql

  mysql:
    container_name: asp-mysql
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - asp-mysql-store:/var/lib/mysql
      # - ./docker/mysql/logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=fc
      - MYSQL_USER=fc
      - MYSQL_PASSWORD=fc@123
      - MYSQL_ROOT_PASSWORD=fc@123
      - TZ=Asia/Tokyo
    ports:
      - '${FORWARD_DB_PORT:-3333}:3306'

volumes:
  asp-mysql-store:
